### ISSUE TITLE
Clear lib_atlas dependency

### ISSUE THREAD

**Issue by 0x72D0** [sonia-auv/proc_image_processing#10]
## Expected Enhancement
lib_atlas is a deprecated library that is not used anymore in this organization. We should remove it.

## Current Behavior
This package use lib_atlas.

## Possible Solution
Replace lib_atlas call by ROS call.

**Comment by Kam0ss** [comment]
We use lib_atlas for threads, such as in provider_vision.

**Comment by 0x72D0** [comment]
ok, but do we want to maintain a package only for the threads or we want to re-implement it and delete lib_atlas?

**Comment by supertoto29** [comment]
@Kam0ss @0x72D0 Is this issue still relevant?

**Comment by Kam0ss** [comment]
No
